#!/bin/sh

{ rm -rf log/*
  rm -rf tmp/*

  gem list -i bundler || gem install bundler && rbenv rehash
  bundle install && rbenv rehash

  rake db:drop:all db:create:all db:setup db:test:prepare
  touch tmp/restart.txt

} >/dev/null 2>&1
